### ISSUE TITLE
C# sample manifest error when sideloading -- Error while reading manifest.json: "name.short" is required... 

### ISSUE THREAD

**Issue by jimbarrett33** [OfficeDev/microsoft-teams-sample-get-started#10]
Trying to sideload bot.zip from the C# sample results in error:

`Error while reading manifest.json: "name.short" is required  "packageName" is required  "icons.outline" is required  "icons.color" is required `

The node.js bot.zip loaded OK so can use that manifest as a starting point.

**Comment by siduppal** [comment]
Hi @jimbarrett33, thanks for reporting! The issue has been fixed.
