### ISSUE TITLE
Tabs and Connector missing from the C# example

### ISSUE THREAD

**Issue by jimbarrett33** [OfficeDev/microsoft-teams-sample-get-started#13]
It seems the node.js example is more complete than the C# example. For example, it is doesn't have tabs (including config page) or connectors. Is the intention to bring more parity to the examples?  Or is this a recommendation to use node.js?

Thanks.

**Comment by RichMoeMSFT** [comment]
Tabs and connectors are just web services that can be written in any language and therefore creating a C# example doesn't add much value as the difference between dev platforms is not a Teams-related difference.   
 The existing C# sample has been configured to talk to an Azure-hosted version of the Node.js tab and connector code.
