### ISSUE TITLE
removeUrl from the config won't load on tab's removal

### ISSUE THREAD

**Issue by psihonavt** [OfficeDev/microsoft-teams-sample-get-started#14]
Hi all

I'm stuck with a problem. I have next config file (one, which specified in the tab's manifest):
```html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Team Config</title>
</head>
<body>
Nothing to configure yet. Please proceed by clicking Save.

<script src="https://statics.teams.microsoft.com/sdk/v0.4/js/MicrosoftTeams.min.js"></script>

<script type="text/javascript">

    microsoftTeams.initialize();

    microsoftTeams.settings.registerOnSaveHandler(function(saveEvent){

        microsoftTeams.getContext(function(ctx){
            console.log("saved");
            console.log(ctx);
        });

        microsoftTeams.settings.setSettings({
            entityId: 'nimble_lookup',
            contentUrl: "https://live.devnimble.com/outlook_teams_addin/nimble_teams.html",
            removeUrl: "https://live.devnimble.com/outlook_teams_addin/remove_teams.html",
            suggestedTabName: "Live 22",
        });
        saveEvent.notifySuccess();
    });
    microsoftTeams.settings.setValidityState(true);

</script>

</body>
</html>
```

A tab can be added to a channel without problems, but upon tab removing from the channel - only default remove dialog shows up (without the content of removeUrl in iframe). 

Please advise.

**Comment by dfederm** [comment]
Can you confirm that in your manifest you define a bot with a static/pinned tab?

If so, this is a known issue. We're working on pushing a fix to production soon.

Sorry for the inconvenience!

**Comment by psihonavt** [comment]
@dfederm Yeah, after hours of debugging, I've pinned the issue to the fact that I have pinned tabs for a bot in manifest :)  Any ETA for a fix? Thanks.

**Comment by dfederm** [comment]
@psihonavt The fix should roll out hopefully today or tomorrow. Note that the bug was at tab configuration time (we basically were dropping some of the fields we were given from setSettings), so once the fix is deployed you'll still need to re-create any tabs exhibiting this behavior.

**Comment by psihonavt** [comment]
@dfederm Great. Can you please update this thread after the fix will have been rolled out?

**Comment by dfederm** [comment]
@psihonavt The fix should be in prod now. Let me know if you're still seeing the issue.

**Comment by psihonavt** [comment]
@dfederm so far so good 👍
